import type { Conversation } from '@grammyjs/conversations';
import type { CustomContext } from '../types.js';
import {
  getSttService,
  getNluParser,
  exerciseService,
  workoutService,
} from '../../services/index.js';
import { createLogger } from '../../logger/logger.js';
import { AppError } from '../../errors/app-errors.js';
import { createExercisePickerKeyboard } from '../keyboards/exercisePicker.js';
import { createWorkoutPreviewKeyboard } from '../keyboards/workoutPreview.js';
import { formatPreview } from '../formatters/workoutFormatter.js';
import type { WorkoutWithRelations } from '../formatters/workoutFormatter.js';
import { PublisherService } from '../../services/publisher.service.js';
import type { Exercise } from '@prisma/client';
import { downloadAndTranscribeVoice } from '../utils/telegram.js';
import { runDisambiguationLoop } from '../utils/disambiguation.js';

const convLogger = createLogger('newWorkoutConversation');

/**
 * Основной FSM-граф(conversation) для создания новой тренировки.
 * Обрабатывает текст/голосовые сообщения, парсинг, уточнение названий и публикацию.
 */
export async function newWorkout(
  conversation: Conversation<CustomContext, CustomContext>,
  ctx: CustomContext,
): Promise<void> {
  convLogger.info({ userId: ctx.user?.id }, 'Started newWorkout conversation');

  if (!ctx.user) {
    throw new AppError('Пользователь не авторизован', 401);
  }

  const userId = ctx.user.id;

  let rawText = '';

  // 1. Получение текста (голос -> STT или напрямую текст)
  if (ctx.message?.voice) {
    rawText = await downloadAndTranscribeVoice(ctx, conversation);
  } else if (ctx.message?.text) {
    rawText = ctx.message.text;
  } else {
    await ctx.reply('⚠️ Пожалуйста, отправьте текст или голосовое сообщение.');
    return;
  }

  if (!rawText.trim()) {
    await ctx.reply('⚠️ Не удалось распознать текст, попробуйте снова.');
    return;
  }

  // 2. NLU Parsing
  await ctx.replyWithChatAction('typing');
  const nluParser = getNluParser();
  const today = new Date().toISOString().split('T')[0];
  const parsedWorkout = await conversation.external(() => nluParser.parse(rawText, today));

  // 3. Создание черновика и разрешение неоднозначностей (Disambiguation)
  const draftResult = await runDisambiguationLoop(
    conversation,
    ctx,
    parsedWorkout,
    'draft', // will be generated by createDraft
    false,
  );

  // 4. Показ превью
  const workoutId = draftResult.workout?.id;
  if (!workoutId) {
    throw new AppError('Не удалось создать черновик тренировки', 500);
  }
  const fullWorkout = await conversation.external(() => workoutService.getDraftForUser(userId));

  if (!fullWorkout) {
    throw new AppError('Не удалось загрузить созданный черновик', 500);
  }

  // 4. Показ итеративного превью и выбор действия
  while (true) {
    const fullWorkout = await conversation.external(() => workoutService.getDraftForUser(userId));

    if (!fullWorkout) {
      throw new AppError('Не удалось загрузить черновик тренировки', 404);
    }

    const previewHtml = formatPreview(fullWorkout as WorkoutWithRelations);
    const previewKb = createWorkoutPreviewKeyboard(workoutId);

    const previewMsg = await ctx.reply(previewHtml, {
      parse_mode: 'HTML',
      reply_markup: previewKb,
    });

    // Сохраняем связки сообщений
    await conversation.external(() =>
      workoutService.updateMessageIds(workoutId, {
        sourceMessageId: ctx.message?.message_id,
        previewMessageId: previewMsg.message_id,
      }),
    );

    // 5. Ожидание действия (Approve, Edit, Cancel)
    const actionCtx = await conversation.waitForCallbackQuery([/^appr:/, /^edit:/, /^canc:/], {
      otherwise: (otherCtx) =>
        otherCtx.reply(
          'Пожалуйста, подтвердите, отредактируйте или отмените тренировку по кнопкам 👆',
          { reply_to_message_id: otherCtx.message?.message_id },
        ),
    });

    const actionData = actionCtx.callbackQuery.data;
    const action = actionData.split(':')[0];

    await actionCtx.answerCallbackQuery();

    if (action === 'appr') {
      // Утверждаем и публикуем
      await conversation.external(() => workoutService.approveDraft(workoutId));
      const publisher = new PublisherService(ctx.api);
      await conversation.external(() => publisher.publish(previewHtml));

      if (ctx.message?.message_id && ctx.chat?.id) {
        await ctx.api.deleteMessage(ctx.chat.id, ctx.message.message_id).catch(() => {});
      }
      await actionCtx.deleteMessage().catch(() => {});

      await ctx.reply('✅ Тренировка успешно опубликована!');
      return;
    } else if (action === 'canc') {
      // Отменяем
      await conversation.external(() => workoutService.cancelDraft(workoutId));
      if (ctx.message?.message_id && ctx.chat?.id) {
        await ctx.api.deleteMessage(ctx.chat.id, ctx.message.message_id).catch(() => {});
      }
      await actionCtx.deleteMessage().catch(() => {});

      await ctx.reply('❌ Тренировка отменена.');
      return;
    } else if (action === 'edit') {
      // Редактируем: запрашиваем дельту изменений
      await ctx.reply('✏️ Что вы хотите изменить? (напишите текстом или запишите голосовое)');

      const editInputCtx = await conversation.waitFor(['message:text', 'message:voice']);
      let editRawText = '';

      if (editInputCtx.message?.voice) {
        await ctx.replyWithChatAction('typing');
        const file = await conversation.external(() => editInputCtx.getFile());
        const { getConfig } = await conversation.external(() => import('../../config/env.js'));
        const response = await conversation.external(() =>
          fetch(`https://api.telegram.org/file/bot${getConfig().BOT_TOKEN}/${file.file_path}`),
        );
        const arrayBuffer = await conversation.external(() => response.arrayBuffer());
        const sttService = getSttService();
        editRawText = await conversation.external(() =>
          sttService.transcribe(Buffer.from(arrayBuffer), 'ru'),
        );
      } else {
        editRawText = editInputCtx.message?.text || '';
      }

      if (!editRawText.trim()) {
        await ctx.reply('⚠️ Не понял вас. Изменения отменены.');
        continue;
      }

      await ctx.replyWithChatAction('typing');
      const parsedEditDelta = await conversation.external(() =>
        nluParser.parseEdit(editRawText, today, JSON.stringify(fullWorkout, null, 2)),
      );

      // Применяем изменения и резолвим новые упражнения
      let editResult = await conversation.external(() =>
        workoutService.applyEdits(workoutId, userId, parsedEditDelta),
      );

      while (editResult.status === 'needs_disambiguation') {
        const ambiguousExercises = editResult.ambiguousExercises || [];

        for (const ambig of ambiguousExercises) {
          if (ambig.mappedExerciseId) continue;

          const resolveResult = await conversation.external(() =>
            exerciseService.resolveExercise(ambig.originalName, userId),
          );

          let options: Array<Pick<Exercise, 'id' | 'canonicalName' | 'displayNameRu'>> = [];
          if (resolveResult.status === 'ambiguous') {
            options = resolveResult.options;
          }

          const kb = createExercisePickerKeyboard(options);
          await ctx.reply(
            `Немного не понял новое упражнение: "${ambig.originalName}". Выберите из списка или создайте:`,
            { reply_markup: kb },
          );

          const responseCtx = await conversation.waitForCallbackQuery([/^map:/, 'new_exercise']);
          const data = responseCtx.callbackQuery.data;
          await responseCtx.answerCallbackQuery();
          await responseCtx.deleteMessage().catch(() => {});

          if (data.startsWith('map:')) {
            const exId = data.split(':')[1];
            await conversation.external(() =>
              exerciseService.confirmMapping(userId, ambig.originalName, exId),
            );
            ambig.mappedExerciseId = exId;
          } else if (data === 'new_exercise') {
            ambig.mappedExerciseId = 'raw';
          }
        }

        editResult = await conversation.external(() =>
          workoutService.applyEdits(workoutId, userId, parsedEditDelta),
        );
      }

      await ctx.reply('🔄 Изменения применены!');
      // Удаляем старое превью и идем на новый круг while(true)
      await actionCtx.deleteMessage().catch(() => {});
    }
  }
}
